#!/bin/bash -l
#SBATCH --nodes=32
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --time=01:30:00
#SBATCH --qos=parallel
#SBATCH --account=math-505
##SBATCH --output=./runs/cqr/cqr_run_33_65535_96_75.txt

run_number=$1
col_number=$2

module load gcc openmpi python py-mpi4py
srun --output="./runs/cqr/cqr_run_${run_number}_65535_${col_number}_512.txt" python choleskyQR.py ${col_number}
